version: '3'

services:
    mysql:
        image: mysql/mysql-server:8.0
        ports:
            - 3306:3306
        volumes:
            - ./var/data/mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: "pucene"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_ROOT_HOST: '%'
